### ISSUE TITLE
if combining sphinx-last-updated-by-git with nbsphinx-link there is an obvious error occuring: The external linked file is not included in git and the path is therefore invalid

### ISSUE THREAD

**Issue by jannefleischer** [mgeier/sphinx-last-updated-by-git#26]
Not really an issue for sphinx-last-updated-by-git because of the out-of-scope use via [nbsphinx-link](https://github.com/vidartf/nbsphinx-link
), nevertheless this may be important for some users and future reference.

sphinx-last-updated-by-git and nbsphinx-link are just not compatible with each other.

```
Traceback (most recent call last):
  File "c:\users\fleischer\appdata\local\esri\conda\envs\monitoring\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "c:\users\fleischer\appdata\local\esri\conda\envs\monitoring\lib\site-packages\sphinx\application.py", line 349, in build
    self.builder.build_update()
  File "c:\users\fleischer\appdata\local\esri\conda\envs\monitoring\lib\site-packages\sphinx\builders\__init__.py", line 299, in build_update
    len(to_build))
  File "c:\users\fleischer\appdata\local\esri\conda\envs\monitoring\lib\site-packages\sphinx\builders\__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "c:\users\fleischer\appdata\local\esri\conda\envs\monitoring\lib\site-packages\sphinx\builders\__init__.py", line 424, in read
    for retval in self.events.emit('env-updated', self.env):
  File "c:\users\fleischer\appdata\local\esri\conda\envs\monitoring\lib\site-packages\sphinx\events.py", line 99, in emit
    results.append(callback(self.app, *args))
  File "c:\users\fleischer\appdata\local\esri\conda\envs\monitoring\lib\site-packages\sphinx_last_updated_by_git.py", line 166, in _env_updated
    update_file_dates(git_dir, dep_dates[git_dir])
  File "c:\users\fleischer\appdata\local\esri\conda\envs\monitoring\lib\site-packages\sphinx_last_updated_by_git.py", line 40, in update_file_dates
    stderr=subprocess.PIPE,
  File "c:\users\fleischer\appdata\local\esri\conda\envs\monitoring\lib\subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "c:\users\fleischer\appdata\local\esri\conda\envs\monitoring\lib\subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\users\fleischer\appdata\local\esri\conda\envs\monitoring\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "c:\users\fleischer\appdata\local\esri\conda\envs\monitoring\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
NotADirectoryError: [WinError 267] Der Verzeichnisname ist ungültig
```

**Comment by mgeier** [comment]
Thanks for the report!

This might be a bug in `nbsphinx-link`: https://github.com/vidartf/nbsphinx-link/pull/14

Can you please try if that takes care of your error?

**Comment by mgeier** [comment]
My fix for nbsphinx-link has not (yet) been accepted, but there is nothing we can do here, so I'm closing this.

**Comment by mgeier** [comment]
Maybe https://github.com/vidartf/nbsphinx-link/pull/26 will fix this (but I didn't try).
