### ISSUE TITLE
Somehow I don't get it to work...

### ISSUE THREAD

**Issue by FredM67** [mgeier/sphinx-last-updated-by-git#63]
Could you please provide an example how to use it ?
I don't get it to work !!

In my config.py, I've
`import zoneinfo`
and
`git_last_updated_timezone = 'FR'`
I've added "tzdata" in my requirements.txt file.

I get these errors in the log:
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/zoneinfo/_common.py", line 12, in load_tzdata
    return resources.files(package_name).joinpath(resource_name).open("rb")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/tzdata/zoneinfo/FR'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/babel/dates.py", line 247, in get_timezone
    return zoneinfo.ZoneInfo(zone)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/zoneinfo/_common.py", line 24, in load_tzdata
    raise ZoneInfoNotFoundError(f"No time zone found with key {key}")
zoneinfo._common.ZoneInfoNotFoundError: 'No time zone found with key FR'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/sphinx/events.py", line 94, in emit
    results.append(listener.handler(self.app, *args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/sphinx_last_updated_by_git.py", line 267, in _config_inited
    config.git_last_updated_timezone = get_timezone(
                                       ^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/babel/dates.py", line 251, in get_timezone
    raise LookupError(f"Unknown timezone {zone}") from exc
LookupError: Unknown timezone FR

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/sphinx/application.py", line 247, in __init__
    self.events.emit('config-inited', self.config)
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/sphinx/events.py", line 105, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function _config_inited at 0x7efc3ad65080> for event 'config-inited' threw an exception (exception: Unknown timezone FR)

Extension error (sphinx_last_updated_by_git):
Handler <function _config_inited at 0x7efc3ad65080> for event 'config-inited' threw an exception (exception: Unknown timezone FR)
make: *** [Makefile:20: dirhtml] Error 2
Error: Process completed with exit code 2.
```

Sorry, if it's a stupid question !
Thx for your help.

**Comment by mgeier** [comment]
It looks like `'FR'` is simply not a time zone, see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

You should try `'Europe/Paris'`.

Several countries have multiple time zones, so I guess it makes more sense to provide a representative city name instead.

I think the example in the README is a bit misleading, so I'm changing it in #64.

**Comment by FredM67** [comment]
Yes, I got it to work with Europe/Paris !
Since in the readme, you wrote `You can also use any string recognized by [babel](https://babel.pocoo.org/), e.g. git_last_updated_timezone = 'NZ'`, I've just tried with `FR` instead of `NZ`.
Thx for your support !
